### ISSUE TITLE
How to flash without any extra hardware

### ISSUE THREAD

**Issue by 9ny4** [krakrukra/PocketAdmin#13]
Title says it. Can i flash new firmware updates without the TP-Link?

**Comment by krakrukra** [comment]
If you have revision 1.3 hardware (96MiB capacity) then you can. 
The process is described in this video: https://www.youtube.com/watch?v=t0oajBFZcZY
and also on this wiki page: https://github.com/krakrukra/PocketAdmin/wiki/bootloader

**Comment by 9ny4** [comment]
Thanks!
