### ISSUE TITLE
Placement of capacitors

### ISSUE THREAD

**Issue by ysard** [krakrukra/PocketAdmin#18]
Hi, first of all, thank you for your great project;
I've studied the PCB and I think I've identified a few "problematic" capacitor placements.

- A 3V3 power rail exits the MCP7000 to the header pin 4 without passing through capacitor C2.
- Capacitor C6 is bypassed because the 3V3 rail touches pin 24 just before it.
- Same thing for C7 and pin 48

I recently encountered similar issues on a personal project.
Here are some doc :

    https://www.protoexpress.com/blog/decoupling-capacitor-placement-guidelines-pcb-design/
    https://www.protoexpress.com/blog/decoupling-capacitor-use/
    https://www.pcbbuy.com/news/Decoupling-Capacitor-Placement-PCB.html
    
Hoping this will be useful to you, even if the PCB is working correctly without these modifications.

**Comment by krakrukra** [comment]
Sure. TBH, you are overthinking this by a lot. Highest frequency on any trace here is 12MHz, that is not super fast.
I could probably take most of the decoupling caps away completely and the circuit would work still. 

And if you want it more specifically, then header pin 4 is not connected to anything during normal operation. It
can not draw any current and does not need decoupling. It can act as a source when a hardware programmer 
device is connected, hence C8 is in place to act as one more bulk decoupling capacitor on the other side of PCB.

I also see that you suggest C6 and C7 are bypassed somehow. Not really. Main power source from host PC through
MCP1700, and bulk decoupling caps, and local decoupling caps are all connected in parallel. And all can act as a
temporary voltage source. Local decoupling caps provide the path with smallest impedance at high frequency. If I
make the 3.3V trace first go to a pad under C6 then to MCU pin 24 it will not decrease impedance further than it
is. Still the same length of trace between C6 and MCU pin 24, still the same loop area for current sourced from C6 
through the MCU and then to load that MCU drives and back to C6 (hence the same inductance).

**Comment by ysard** [comment]
Thank you for your reply and explanations, in fact I think there's quite a bit of FUD about the position of the capacitors.

I understand your arguments, especially since the circuit doesn't work at very high frequencies.
If you have any documentation I'd be happy to read it ;)

**Comment by krakrukra** [comment]
Yes, it's kind of a complicated topic, easy to get confused. And it's not like I am the greatest expert on this
either, I was reading articles much like you found, watching tutorials and stuff like that. Also read one 
book called "Electromagnetic Compatibility Engineering" I think it had a section on decoupling caps
which was helpful.

**Comment by ysard** [comment]
Thanks for the recommendation, there's indeed a long chapter on the subject that I'm currently reading.

I guess you can close the issue ;)
