### ISSUE TITLE
Pocket Admin not typing anything 

### ISSUE THREAD

**Issue by jwlanders1** [krakrukra/PocketAdmin#7]
Hi, I just ordered these and I can’t figure out how to make them type. I followed the videos, but I can’t find anything on how to fix it.

**Comment by krakrukra** [comment]
Does it show up as storage device? And also, 
tell me which OS you are using and 
what is the payload you are trying to run.

**Comment by jwlanders1** [comment]
Yes it shows up as pocket admin but doesn’t type. I’m using windows 10. The
payload is just a test to open run and type cmd.  I’ve tested it in notepad
to see if it would type there, but it doesn’t.

**Comment by krakrukra** [comment]
If you are on windows 10 it might be that you have file extentions turned off,
eg. file that should be called payload.txt is actually called payload.txt.txt
so, you could try to rename "payload.txt" to just "payload" and see if it helps.

also you did not mention any startup delay. try using this payload script:
WAITFOR_INIT
DELAY 1000
STRING test string into some text editor

make sure your cursor is in a notepad window before you plug the device in

**Comment by jwlanders1** [comment]
it was “.txt.txt” didn’t even notice. thank you!
