### ISSUE TITLE
Can you press the button without opening up the usb?

### ISSUE THREAD

**Issue by calegxm999** [krakrukra/PocketAdmin#8]
You know how there is a button inside the usb to stop it from injecting the payload?
Can you press the button without opening up the usb?

**Comment by krakrukra** [comment]
No, but this is why ALLOW_EXIT command was implemented.
I usually start a payload with this:
WAITFOR_INIT
ALLOW_EXIT

That makes the device wait for initialization time and then wait for
1 extra second. If you toggle capslock during this 1 second, payload
will not be run. So you can prevent payload execution by spamming 
capslock key during device insertion.

**Comment by calegxm999** [comment]
Thanks.......
