### ISSUE TITLE
Button Not Working

### ISSUE THREAD

**Issue by Vanceagher** [krakrukra/PocketAdmin#9]
I recently enabled the HID only mode but when I plugged in the USB while holding down the button inside, nothing happened. Before this I also notice that holding down the button while inserting the USB seemed to do nothing, the USB would still execute the on insertion payload.

**Comment by krakrukra** [comment]
It might be that some solder joint got damaged. But maybe this is 
just because the button is not held down long enough. Try to do this:
hold the button, plug the device in, wait for 5 seconds, release. Check
if it helped or not.

**Comment by Vanceagher** [comment]
Just tried that, didn't seem to do anything, it must be a physical issue with the PocketAdmin.

**Comment by krakrukra** [comment]
Well, then it is probably pin 12 on the microcontroller that got a damaged solder joint.
![pin12](https://user-images.githubusercontent.com/42712242/93219796-429ea800-f75b-11ea-951a-f5f6fd6031d1.jpg)
It is not really hard to fix, though I am not sure if you have a soldering iron around.

Good news is that this button is not very necessary for 1.3 revision devices. You can
get out of HID-only mode by tapping capslock 20 times or more (while device is inserted)
And if you want to prevent payload from being run you can use ALLOW_EXIT command.
That is, you start every payload with a sequence of WAITFOR_INIT and then ALLOW_EXIT
commands. This way you can prevent payload execution by spamming capslock while
you insert the device.

**Comment by Vanceagher** [comment]
Great, the capslock trick worked.

**Comment by krakrukra** [comment]
Though, if you are able to reflow that solder joint then you could restore MSD-button
operation as well. If you don't have that, maybe just press down on that pin with something
sharp, like tweezers or needle and it could restore the connection again
